import os
import sys
import ycm_core

# Attemp to load the local file that will have the correct path for this machine.
local_flags = []
try:
    sys.path.append(os.getcwd())
    import ycm_extra_conf_local
    local_flags = ycm_extra_conf_local.GetYCMLocalFlags()
except Exception as err:
    print(err)

flags = [
    '-Wall',
    '-Wextra',
    '-Wmissing-prototypes',
    '-x', 'c++',
    '--std=c++17',
]

flags += local_flags

flags += [
    '-I', os.path.join(os.getcwd()),

    '-D', 'ROTHKO_SDL_ENABLED',
    '-D', 'ROTHKO_VULKAN_ENABLED',
    '-D', 'ROTHKO_OPENGL_ENABLED',

    '-isystem', os.path.join(os.getcwd(), 'third_party'),
    '-isystem', os.path.join(os.getcwd(), 'third_party', 'include'),
    '-isystem', os.path.join(os.getcwd(), 'third_party', 'imgui'),
    '-isystem', os.path.join(os.getcwd(), 'third_party', 'imgui', 'examples'),
    '-isystem', os.path.join(os.getcwd(), 'third_party', 'catch2'),
]


################################################################################
# YCM Classic Implementation
################################################################################

# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      relative_to = DirectoryOfThisScript()
      return {
        'flags': MakeRelativePathsInFlagsAbsolute( flags, relative_to ),
        'do_cache': True
      }

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }
